version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      AUTH_USERS: $AUTH_USERS  # defaults to None
      TG_BOT_TOKEN: $TG_BOT_TOKEN 
      WEBHOOK: $ANYTHING
      DB_URI: $DB_URI
